In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/wildfire_data.csv")

print(df.shape)
print(df.columns.tolist())
df.head()

(125476, 30)
['OBJECTID', 'Year', 'AGENCY', 'UNIT_ID', 'FIRE_NAME', 'INC_NUM', 'ALARM_DATE', 'CONT_DATE', 'CAUSE', 'C_METHOD', 'OBJECTIVE', 'GIS_ACRES', 'COMMENTS', 'COMPLEX_NA', 'FIRE_NUM', 'COMPLEX_ID', 'DECADES', 'Shape__Are', 'Shape__Len', 'latitude', 'longitude', 'zip', 'Alarm_Date2', 'year_month', 'AGENCY_ID', 'FIRE_NAME_ID', 'avg_tmax_c', 'avg_tmin_c', 'tot_prcp_mm', 'station']

/var/folders/8g/24hb2lpj4wx0b6njqx5m9m6c0000gn/T/ipykernel_77772/16568466.py:3: DtypeWarning: Columns (5,13,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/wildfire_data.csv")

,OBJECTID,Year,AGENCY,UNIT_ID,FIRE_NAME,INC_NUM,ALARM_DATE,CONT_DATE,CAUSE,C_METHOD,...,longitude,zip,Alarm_Date2,year_month,AGENCY_ID,FIRE_NAME_ID,avg_tmax_c,avg_tmin_c,tot_prcp_mm,station
0,1653.0,2019.0,CDF,MEU,GRADE,8307.0,7/16/17,7/21/17,10.0,7.0,...,-123.266813,95470.0,2017-07-16,2017-07,0.0,92.0,NaN,NaN,NaN,NaN
1,1982.0,2018.0,CCO,VNC,SOUTH,113365.0,12/21/17,12/21/17,14.0,6.0,...,-119.051707,93060.0,2017-12-21,2017-12,2.0,102.0,NaN,NaN,NaN,NaN
2,1980.0,2018.0,CCO,VNC,BALCOM,113691.0,12/22/17,12/22/17,14.0,6.0,...,-118.977639,93066.0,2017-12-22,2017-12,2.0,1400.0,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,90001.0,NaN,2018-01,NaN,NaN,21.748387,11.432258,35.5,72295.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,90002.0,NaN,2018-01,NaN,NaN,21.748387,11.432258,35.5,72295.0

In [3]:
print(df.isna().mean().sort_values(ascending=False).head(20))

FIRE_NUM        1.000000
COMPLEX_ID      0.999673
COMPLEX_NA      0.999562
COMMENTS        0.996334
INC_NUM         0.982578
CONT_DATE       0.982523
UNIT_ID         0.982395
FIRE_NAME       0.982379
ALARM_DATE      0.982371
OBJECTIVE       0.982371
Alarm_Date2     0.982371
C_METHOD        0.982339
longitude       0.982323
AGENCY_ID       0.982323
Shape__Len      0.982323
FIRE_NAME_ID    0.982323
latitude        0.982323
OBJECTID        0.982323
Shape__Are      0.982323
DECADES         0.982323
dtype: float64

In [4]:
fire_df = df[df["FIRE_NAME"].notna()].copy()
weather_df = df[df["year_month"].notna()].copy()

print("fire rows:", fire_df.shape)
print("weather rows:", weather_df.shape)

fire_df.head()

fire rows: (2211, 30)
weather rows: (125470, 30)

,OBJECTID,Year,AGENCY,UNIT_ID,FIRE_NAME,INC_NUM,ALARM_DATE,CONT_DATE,CAUSE,C_METHOD,...,longitude,zip,Alarm_Date2,year_month,AGENCY_ID,FIRE_NAME_ID,avg_tmax_c,avg_tmin_c,tot_prcp_mm,station
0,1653.0,2019.0,CDF,MEU,GRADE,8307.0,7/16/17,7/21/17,10.0,7.0,...,-123.266813,95470.0,2017-07-16,2017-07,0.0,92.0,NaN,NaN,NaN,NaN
1,1982.0,2018.0,CCO,VNC,SOUTH,113365.0,12/21/17,12/21/17,14.0,6.0,...,-119.051707,93060.0,2017-12-21,2017-12,2.0,102.0,NaN,NaN,NaN,NaN
2,1980.0,2018.0,CCO,VNC,BALCOM,113691.0,12/22/17,12/22/17,14.0,6.0,...,-118.977639,93066.0,2017-12-22,2017-12,2.0,1400.0,NaN,NaN,NaN,NaN
133,2183.0,2018.0,NPS,SMP,SERRA,NaN,1/29/18,1/30/18,14.0,8.0,...,-118.688858,90265.0,2018-01-29,2018-01,5.0,1515.0,21.748387,11.432258,35.5,72295.0
388,1930.0,2018.0,CCO,VNC,ERBES,9049.0,1/31/18,1/31/18,14.0,6.0,...,-118.846422,91360.0,2018-01-31,2018-01,2.0,749.0,21.448387,9.829032,18.8,72391.0